[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.120.2",
    "modaic>=0.4.0",
    "pydantic>=2.12.3",
]
